corridor_length: 200.0
corridor_width: 2.5
robot_view_range: 5.0
warmup_steps: 1000
action_repeat: 10
num_envs: 6
obstacles_mode: "random"
obstacles_mode_param:
  obstacle_sep: 3.0
  obstacle_size_x: 0.5
  obstacle_size_y: 0.5
  obstacle_size_z: 0.5