simulation:
  max_steps: 30000
  env_precision: 0.2

# Pointer to specific configurations
model:
  config_file: "agents/policy_mlp_small.yaml" # or agents/policy_transformer_large.yaml

rewards:
  config_file: "rewards/velocity_focused.yaml"

training:
  lr: 0.0003